# Generated by Django 3.2 on 2023-02-20 00:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceFixRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('stamp_type', models.CharField(choices=[('AT', 'attendance'), ('LE', 'leave')], max_length=2)),
                ('is_accepted', models.BooleanField(default=False)),
                ('revision_time', models.DateTimeField()),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('checked_time', models.DateTimeField(null=True)),
                ('attendance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.attendances')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
