# Generated by Django 3.2 on 2023-02-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendances',
            name='emotions',
            field=models.JSONField(default=0, verbose_name=models.CharField()),
            preserve_default=False,
        ),
    ]
