# Generated by Django 3.2 on 2023-02-22 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendances_emotions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendances',
            name='emotions',
            field=models.JSONField(null=True, verbose_name=models.CharField()),
        ),
    ]
