# Generated by Django 3.2 on 2023-02-22 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendances_emotions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendances',
            name='emotions',
        ),
        migrations.AddField(
            model_name='attendances',
            name='attendance_emotions',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='attendances',
            name='leave_emotions',
            field=models.JSONField(null=True),
        ),
    ]
