# Generated by Django 3.2 on 2023-02-22 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_auto_20230222_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendances',
            name='attendance_emotions',
        ),
        migrations.RemoveField(
            model_name='attendances',
            name='leave_emotions',
        ),
    ]
