# Generated by Django 3.2 on 2023-02-23 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_auto_20230222_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendances',
            name='attendance_emotions',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='attendances',
            name='leave_emotions',
            field=models.JSONField(null=True),
        ),
    ]
