# Generated by Django 3.2 on 2023-02-23 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_attendances_leave_emotions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendances',
            name='attendance_emotions',
            field=models.JSONField(max_length=64, null=True),
        ),
    ]
