# Generated by Django 3.2 on 2023-02-23 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_alter_attendances_attendance_emotions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendances',
            name='attendance_emotions',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
