# Generated by Django 3.2 on 2023-02-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_alter_attendances_attendance_emotions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendances',
            name='attendance_emotions',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='attendances',
            name='leave_emotions',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
