# Generated by Django 3.2 on 2023-02-23 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_auto_20230223_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendances',
            name='attendance_emotions',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='attendances',
            name='leave_emotions',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
